version: '2'

services:
  app:
    ports:
      - "8443:8443"
    build:
      context: .
    container_name: app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CERTIFICATE_SECRET=${CERTIFICATE_SECRET}
      - CERTIFICATE_FILE_NAME=${CERTIFICATE_FILE_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - spring_profiles_active=${spring_profiles_active}
    depends_on:
      - cache
  cache:
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: always
    command:
      - redis-server

